// 365 Biblical quotes - one for each day of the year
export const dailyQuotes = [
  // Janeiro (1-31)
  { text: "E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos pensamentos em Cristo Jesus.", ref: "Filipenses 4:7" },
  { text: "Porque eu sei os planos que tenho para vocês, planos de fazê-los prosperar e não de lhes causar dano, planos de dar-lhes esperança e um futuro.", ref: "Jeremias 29:11" },
  { text: "O Senhor é o meu pastor; nada me faltará.", ref: "Salmos 23:1" },
  { text: "Tudo posso naquele que me fortalece.", ref: "Filipenses 4:13" },
  { text: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.", ref: "Provérbios 3:5" },
  { text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito.", ref: "João 3:16" },
  { text: "O Senhor é a minha luz e a minha salvação; a quem temerei?", ref: "Salmos 27:1" },
  { text: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.", ref: "Isaías 41:10" },
  { text: "Bem-aventurados os misericordiosos, porque eles alcançarão misericórdia.", ref: "Mateus 5:7" },
  { text: "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus.", ref: "Romanos 8:28" },
  { text: "Lança o teu cuidado sobre o Senhor, e ele te susterá.", ref: "Salmos 55:22" },
  { text: "Eu sou o caminho, a verdade e a vida.", ref: "João 14:6" },
  { text: "Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos!", ref: "Filipenses 4:4" },
  { text: "O amor é paciente, o amor é bondoso.", ref: "1 Coríntios 13:4" },
  { text: "Buscai primeiro o Reino de Deus e a sua justiça.", ref: "Mateus 6:33" },
  { text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.", ref: "Mateus 11:28" },
  { text: "Porque onde estiver o vosso tesouro, aí estará também o vosso coração.", ref: "Mateus 6:21" },
  { text: "Sede fortes e corajosos. Não tenham medo.", ref: "Deuteronômio 31:6" },
  { text: "O justo viverá pela fé.", ref: "Romanos 1:17" },
  { text: "Dai graças em tudo; porque esta é a vontade de Deus em Cristo Jesus para convosco.", ref: "1 Tessalonicenses 5:18" },
  { text: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.", ref: "Hebreus 11:1" },
  { text: "Porque a palavra de Deus é viva e eficaz.", ref: "Hebreus 4:12" },
  { text: "Eis que estou à porta e bato.", ref: "Apocalipse 3:20" },
  { text: "As misericórdias do Senhor são a causa de não sermos consumidos.", ref: "Lamentações 3:22" },
  { text: "Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração.", ref: "Salmos 37:4" },
  { text: "Porque o Senhor dá a sabedoria; da sua boca procedem o conhecimento e o entendimento.", ref: "Provérbios 2:6" },
  { text: "Ensina-me, Senhor, o teu caminho, e guia-me pela vereda direita.", ref: "Salmos 27:11" },
  { text: "Aquele que começou a boa obra em vocês, vai completá-la até o dia de Cristo Jesus.", ref: "Filipenses 1:6" },
  { text: "Porque pela graça sois salvos, por meio da fé.", ref: "Efésios 2:8" },
  { text: "O Senhor é bom, uma fortaleza no dia da angústia.", ref: "Naum 1:7" },
  { text: "Portanto, se alguém está em Cristo, é nova criatura.", ref: "2 Coríntios 5:17" },
  // Fevereiro (32-59)
  { text: "Clama a mim, e responder-te-ei, e anunciar-te-ei coisas grandes.", ref: "Jeremias 33:3" },
  { text: "Não vos conformeis com este mundo, mas transformai-vos pela renovação da vossa mente.", ref: "Romanos 12:2" },
  { text: "O Senhor te abençoe e te guarde.", ref: "Números 6:24" },
  { text: "Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum.", ref: "Salmos 23:4" },
  { text: "Eu vim para que tenham vida, e a tenham com abundância.", ref: "João 10:10" },
  { text: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, amor e moderação.", ref: "2 Timóteo 1:7" },
  { text: "Espera no Senhor, anima-te, e ele fortalecerá o teu coração.", ref: "Salmos 27:14" },
  { text: "Todo aquele que invocar o nome do Senhor será salvo.", ref: "Romanos 10:13" },
  { text: "Não te deixarei, nem te desampararei.", ref: "Hebreus 13:5" },
  { text: "Mas os que esperam no Senhor renovarão as suas forças.", ref: "Isaías 40:31" },
  { text: "O Senhor é fiel, e vos fortalecerá e vos guardará do mal.", ref: "2 Tessalonicenses 3:3" },
  { text: "Maior é o que está em vós do que o que está no mundo.", ref: "1 João 4:4" },
  { text: "Pedi, e dar-se-vos-á; buscai, e encontrareis.", ref: "Mateus 7:7" },
  { text: "Toda boa dádiva e todo dom perfeito vêm do alto.", ref: "Tiago 1:17" },
  { text: "Eu sou a ressurreição e a vida.", ref: "João 11:25" },
  { text: "O fruto do Espírito é amor, alegria, paz, paciência, benignidade.", ref: "Gálatas 5:22" },
  { text: "Sede bondosos uns para com os outros, compassivos.", ref: "Efésios 4:32" },
  { text: "Mas buscai primeiro o reino de Deus.", ref: "Mateus 6:33" },
  { text: "O Senhor é a minha força e o meu cântico.", ref: "Salmos 118:14" },
  { text: "Crê no Senhor Jesus Cristo e serás salvo.", ref: "Atos 16:31" },
  { text: "Acheguemo-nos, pois, com confiança ao trono da graça.", ref: "Hebreus 4:16" },
  { text: "Respondeu Jesus: Eu sou o pão da vida.", ref: "João 6:35" },
  { text: "Não andem ansiosos por coisa alguma.", ref: "Filipenses 4:6" },
  { text: "A tua palavra é lâmpada para os meus pés e luz para o meu caminho.", ref: "Salmos 119:105" },
  { text: "Porque somos feitura sua, criados em Cristo Jesus para as boas obras.", ref: "Efésios 2:10" },
  { text: "Nisto conhecerão todos que sois meus discípulos, se vos amardes uns aos outros.", ref: "João 13:35" },
  { text: "Tudo me é lícito, mas nem tudo convém.", ref: "1 Coríntios 6:12" },
  { text: "A oração feita por um justo pode muito em seus efeitos.", ref: "Tiago 5:16" },
  // Março (60-90)
  { text: "Eis que estou convosco todos os dias, até à consumação dos séculos.", ref: "Mateus 28:20" },
  { text: "Porque não me envergonho do evangelho de Cristo.", ref: "Romanos 1:16" },
  { text: "O céu e a terra passarão, mas as minhas palavras não passarão.", ref: "Mateus 24:35" },
  { text: "Sede imitadores de Deus, como filhos amados.", ref: "Efésios 5:1" },
  { text: "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar.", ref: "1 João 1:9" },
  { text: "Jesus Cristo é o mesmo ontem, hoje, e eternamente.", ref: "Hebreus 13:8" },
  { text: "Mas a nossa cidade está nos céus.", ref: "Filipenses 3:20" },
  { text: "Ama ao Senhor teu Deus de todo o teu coração.", ref: "Mateus 22:37" },
  { text: "O Senhor dos Exércitos está conosco.", ref: "Salmos 46:7" },
  { text: "Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.", ref: "Mateus 5:9" },
  { text: "Porque nada trouxemos para este mundo e nada podemos levar dele.", ref: "1 Timóteo 6:7" },
  { text: "Guardemos firme a confissão da nossa esperança.", ref: "Hebreus 10:23" },
  { text: "Muitas são as aflições do justo, mas o Senhor o livra de todas.", ref: "Salmos 34:19" },
  { text: "Não julgueis, para que não sejais julgados.", ref: "Mateus 7:1" },
  { text: "Santificai a Cristo, como Senhor, em vosso coração.", ref: "1 Pedro 3:15" },
  { text: "Portanto, nenhuma condenação há para os que estão em Cristo Jesus.", ref: "Romanos 8:1" },
  { text: "Eu venci o mundo.", ref: "João 16:33" },
  { text: "É pela fé que andamos, não pela vista.", ref: "2 Coríntios 5:7" },
  { text: "Porque o Reino de Deus não é comida nem bebida, mas justiça, paz e alegria.", ref: "Romanos 14:17" },
  { text: "Considerai, pois, grandíssima alegria o passardes por várias provações.", ref: "Tiago 1:2" },
  { text: "O Senhor é o meu rochedo, a minha fortaleza e o meu libertador.", ref: "Salmos 18:2" },
  { text: "Vós sois a luz do mundo.", ref: "Mateus 5:14" },
  { text: "Assim resplandeça a vossa luz diante dos homens.", ref: "Mateus 5:16" },
  { text: "Porque tu criaste todas as coisas.", ref: "Apocalipse 4:11" },
  { text: "Não cessamos de orar por vós.", ref: "Colossenses 1:9" },
  { text: "Dá instrução ao sábio, e ele se fará mais sábio ainda.", ref: "Provérbios 9:9" },
  { text: "Amai-vos uns aos outros como eu vos amei.", ref: "João 15:12" },
  { text: "Examinai tudo. Retende o bem.", ref: "1 Tessalonicenses 5:21" },
  { text: "Sujeitai-vos, pois, a Deus. Resisti ao diabo, e ele fugirá de vós.", ref: "Tiago 4:7" },
  { text: "Mas, quando vier o Espírito da verdade, ele vos guiará em toda a verdade.", ref: "João 16:13" },
  { text: "A graça de nosso Senhor Jesus Cristo seja com todos vós.", ref: "Apocalipse 22:21" },
  // Abril (91-120)
  { text: "E eis que eu sou contigo, e te guardarei por onde quer que fores.", ref: "Gênesis 28:15" },
  { text: "Na casa de meu Pai há muitas moradas.", ref: "João 14:2" },
  { text: "Eu sou a videira, vós as varas.", ref: "João 15:5" },
  { text: "Não me escolhestes vós a mim, mas eu vos escolhi a vós.", ref: "João 15:16" },
  { text: "Ora, o Deus de esperança vos encha de todo o gozo e paz.", ref: "Romanos 15:13" },
  { text: "Porque somos embaixadores em nome de Cristo.", ref: "2 Coríntios 5:20" },
  { text: "Não há judeu nem grego; não há servo nem livre.", ref: "Gálatas 3:28" },
  { text: "E, acima de tudo isto, revesti-vos de amor.", ref: "Colossenses 3:14" },
  { text: "O Senhor é tardo em irar-se, mas grande em poder.", ref: "Naum 1:3" },
  { text: "Todas as promessas de Deus são sim e amém nele.", ref: "2 Coríntios 1:20" },
  { text: "Porque onde está o teu tesouro, aí estará também o teu coração.", ref: "Lucas 12:34" },
  { text: "Crescei na graça e no conhecimento de nosso Senhor.", ref: "2 Pedro 3:18" },
  { text: "Com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.", ref: "Romanos 10:10" },
  { text: "Revesti-vos de toda a armadura de Deus.", ref: "Efésios 6:11" },
  { text: "Bendito o Deus e Pai de nosso Senhor Jesus Cristo.", ref: "Efésios 1:3" },
  { text: "É mais bem-aventurado dar do que receber.", ref: "Atos 20:35" },
  { text: "Sede, pois, imitadores de Deus, como filhos amados.", ref: "Efésios 5:1" },
  { text: "Ora, àquele que é poderoso para vos guardar de tropeçar.", ref: "Judas 1:24" },
  { text: "Respondeu Jesus: Está escrito: Nem só de pão viverá o homem.", ref: "Mateus 4:4" },
  { text: "Deus é amor.", ref: "1 João 4:8" },
  { text: "Não temas, crê somente.", ref: "Marcos 5:36" },
  { text: "As coisas velhas já passaram; eis que tudo se fez novo.", ref: "2 Coríntios 5:17" },
  { text: "Porque nele foram criadas todas as coisas.", ref: "Colossenses 1:16" },
  { text: "Eu e o Pai somos um.", ref: "João 10:30" },
  { text: "E nos salvou, não pelas obras de justiça que houvéssemos feito.", ref: "Tito 3:5" },
  { text: "Sem fé é impossível agradar a Deus.", ref: "Hebreus 11:6" },
  { text: "Deus resiste aos soberbos, mas dá graça aos humildes.", ref: "Tiago 4:6" },
  { text: "Ora, a perseverança produz experiência, e a experiência, esperança.", ref: "Romanos 5:4" },
  { text: "Assim como os céus são mais altos do que a terra.", ref: "Isaías 55:9" },
  { text: "O Senhor é misericordioso e compassivo.", ref: "Salmos 103:8" },
  // Maio (121-151)
  { text: "Porque dele, e por ele, e para ele são todas as coisas.", ref: "Romanos 11:36" },
  { text: "Ele mesmo levou em seu corpo os nossos pecados sobre o madeiro.", ref: "1 Pedro 2:24" },
  { text: "Porque há um só Deus e um só mediador entre Deus e os homens.", ref: "1 Timóteo 2:5" },
  { text: "Assim diz o Senhor: Ponde-vos nos caminhos e vede.", ref: "Jeremias 6:16" },
  { text: "Fazei tudo para a glória de Deus.", ref: "1 Coríntios 10:31" },
  { text: "Ora, a fé é a certeza daquilo que esperamos.", ref: "Hebreus 11:1" },
  { text: "E dou-lhes a vida eterna, e nunca hão de perecer.", ref: "João 10:28" },
  { text: "Bem-aventurados os que têm fome e sede de justiça.", ref: "Mateus 5:6" },
  { text: "Nisto consiste o amor: não em que nós tenhamos amado a Deus.", ref: "1 João 4:10" },
  { text: "Vós sois o sal da terra.", ref: "Mateus 5:13" },
  { text: "Ora, se Deus assim veste a erva do campo.", ref: "Mateus 6:30" },
  { text: "Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?", ref: "Romanos 8:31" },
  { text: "Não deis lugar ao diabo.", ref: "Efésios 4:27" },
  { text: "Segui a paz com todos, e a santificação.", ref: "Hebreus 12:14" },
  { text: "Aquele que ama a correção ama o conhecimento.", ref: "Provérbios 12:1" },
  { text: "Melhor é o fim das coisas do que o princípio delas.", ref: "Eclesiastes 7:8" },
  { text: "Quão preciosos me são, ó Deus, os teus pensamentos!", ref: "Salmos 139:17" },
  { text: "Porque tu és o meu auxílio; jubilo à sombra das tuas asas.", ref: "Salmos 63:7" },
  { text: "Ensinando-os a guardar todas as coisas que eu vos tenho mandado.", ref: "Mateus 28:20" },
  { text: "A graça do Senhor Jesus Cristo seja com o vosso espírito.", ref: "Filemom 1:25" },
  { text: "O temor do Senhor é o princípio da sabedoria.", ref: "Provérbios 9:10" },
  { text: "Não temo milhares de pessoas que se acampam contra mim.", ref: "Salmos 3:6" },
  { text: "Certamente a bondade e a misericórdia me seguirão todos os dias da minha vida.", ref: "Salmos 23:6" },
  { text: "Ora, o Senhor é o Espírito; e onde está o Espírito do Senhor, aí há liberdade.", ref: "2 Coríntios 3:17" },
  { text: "E foram batizados por ele no Jordão, confessando os seus pecados.", ref: "Mateus 3:6" },
  { text: "Exaltado seja Deus, a minha rocha.", ref: "Salmos 18:46" },
  { text: "Amarás o teu próximo como a ti mesmo.", ref: "Mateus 22:39" },
  { text: "Eu rogarei ao Pai, e ele vos dará outro Consolador.", ref: "João 14:16" },
  { text: "E o Espírito Santo desceu sobre ele em forma corpórea, como pomba.", ref: "Lucas 3:22" },
  { text: "Quem está em Cristo, nova criatura é.", ref: "2 Coríntios 5:17" },
  { text: "Pois o Filho do Homem veio buscar e salvar o perdido.", ref: "Lucas 19:10" },
  // Junho (152-181)
  { text: "Eu sou o Alfa e o Ômega, o Primeiro e o Último.", ref: "Apocalipse 1:11" },
  { text: "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna.", ref: "Romanos 6:23" },
  { text: "Tu és o meu Senhor; não tenho outro bem além de ti.", ref: "Salmos 16:2" },
  { text: "E da sua plenitude todos nós recebemos, e graça sobre graça.", ref: "João 1:16" },
  { text: "E, se andarmos na luz, como ele está na luz.", ref: "1 João 1:7" },
  { text: "Porque Deus não nos destinou para a ira.", ref: "1 Tessalonicenses 5:9" },
  { text: "E as portas do inferno não prevalecerão contra ela.", ref: "Mateus 16:18" },
  { text: "Para que sejais filhos do vosso Pai que está nos céus.", ref: "Mateus 5:45" },
  { text: "Que é o homem, para que dele te lembres?", ref: "Salmos 8:4" },
  { text: "E todo o que vive e crê em mim nunca morrerá.", ref: "João 11:26" },
  { text: "Os que semeiam em lágrimas, com cânticos de júbilo ceifarão.", ref: "Salmos 126:5" },
  { text: "Levantarei os meus olhos para os montes; de onde me virá o socorro?", ref: "Salmos 121:1" },
  { text: "Fortalecei as mãos fracas e firmai os joelhos vacilantes.", ref: "Isaías 35:3" },
  { text: "Enche-te de temor ao Senhor o dia todo.", ref: "Provérbios 23:17" },
  { text: "Eis que vos dou poder para pisar serpentes e escorpiões.", ref: "Lucas 10:19" },
  { text: "Se permanecerdes em mim, e as minhas palavras permanecerem em vós.", ref: "João 15:7" },
  { text: "O justo florescerá como a palmeira.", ref: "Salmos 92:12" },
  { text: "Porque os olhos do Senhor estão sobre os justos.", ref: "1 Pedro 3:12" },
  { text: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios.", ref: "Salmos 103:2" },
  { text: "O Senhor é a minha rocha, a minha cidadela e o meu libertador.", ref: "2 Samuel 22:2" },
  { text: "Permanecei em mim, e eu permanecerei em vós.", ref: "João 15:4" },
  { text: "Aquietai-vos e sabei que eu sou Deus.", ref: "Salmos 46:10" },
  { text: "Buscai ao Senhor enquanto se pode achar.", ref: "Isaías 55:6" },
  { text: "Porque eu vivo, vós também vivereis.", ref: "João 14:19" },
  { text: "Porque somos para Deus o bom perfume de Cristo.", ref: "2 Coríntios 2:15" },
  { text: "Se alguém tem sede, venha a mim e beba.", ref: "João 7:37" },
  { text: "A terra é do Senhor e a sua plenitude.", ref: "Salmos 24:1" },
  { text: "E eis que eu estou convosco todos os dias.", ref: "Mateus 28:20" },
  { text: "Não vos esqueçais da hospitalidade.", ref: "Hebreus 13:2" },
  { text: "E graça e verdade vieram por meio de Jesus Cristo.", ref: "João 1:17" },
  // Julho (182-212)
  { text: "Porque o Senhor dá a sabedoria; da sua boca vem o conhecimento e o entendimento.", ref: "Provérbios 2:6" },
  { text: "Com grande clamor e lágrimas, ofereceu orações e súplicas.", ref: "Hebreus 5:7" },
  { text: "Não cobices a prata ou o ouro.", ref: "Atos 3:6" },
  { text: "Não há nenhum outro nome debaixo do céu dado entre os homens.", ref: "Atos 4:12" },
  { text: "O Senhor dos Exércitos está conosco; o Deus de Jacó é o nosso refúgio.", ref: "Salmos 46:11" },
  { text: "O próprio Deus da paz vos santifique completamente.", ref: "1 Tessalonicenses 5:23" },
  { text: "Porque a nossa leve e momentânea tribulação produz um eterno peso de glória.", ref: "2 Coríntios 4:17" },
  { text: "Nada faças por contenda ou por vanglória.", ref: "Filipenses 2:3" },
  { text: "Antes de tudo, que se façam súplicas, orações, intercessões e ações de graças.", ref: "1 Timóteo 2:1" },
  { text: "Vigiai e orai para que não entreis em tentação.", ref: "Mateus 26:41" },
  { text: "E nos fez reis e sacerdotes para Deus.", ref: "Apocalipse 1:6" },
  { text: "Aquele que é fiel no mínimo também é fiel no muito.", ref: "Lucas 16:10" },
  { text: "Eu sou o bom pastor; o bom pastor dá a sua vida pelas ovelhas.", ref: "João 10:11" },
  { text: "Mas buscai primeiro o seu Reino e a sua justiça.", ref: "Mateus 6:33" },
  { text: "Fiel é Deus, pelo qual fostes chamados.", ref: "1 Coríntios 1:9" },
  { text: "Cheios de frutos de justiça, que são por meio de Jesus Cristo.", ref: "Filipenses 1:11" },
  { text: "Cada um cuide, não somente dos seus interesses.", ref: "Filipenses 2:4" },
  { text: "Portanto, se alguém está em Cristo, é nova criatura.", ref: "2 Coríntios 5:17" },
  { text: "Adorai o Senhor na beleza da santidade.", ref: "Salmos 96:9" },
  { text: "E a verdade vos libertará.", ref: "João 8:32" },
  { text: "Então disse Jesus: Eu sou o pão da vida.", ref: "João 6:35" },
  { text: "Quando der graças, que comais, que bebais.", ref: "1 Coríntios 10:31" },
  { text: "Portanto, vocês já não são estrangeiros nem forasteiros.", ref: "Efésios 2:19" },
  { text: "Lembrai-vos da mulher de Ló.", ref: "Lucas 17:32" },
  { text: "O Senhor está perto de todos os que o invocam.", ref: "Salmos 145:18" },
  { text: "Tende ânimo, eu venci o mundo.", ref: "João 16:33" },
  { text: "Porque onde há inveja e ambição, aí há perturbação.", ref: "Tiago 3:16" },
  { text: "Se vivemos, para o Senhor vivemos.", ref: "Romanos 14:8" },
  { text: "A bênção do Senhor enriquece; e ele não acrescenta dores.", ref: "Provérbios 10:22" },
  { text: "Lembra-te do teu Criador nos dias da tua mocidade.", ref: "Eclesiastes 12:1" },
  { text: "Tudo quanto te vier à mão para fazer, faze-o com toda a tua força.", ref: "Eclesiastes 9:10" },
  // Agosto (213-243)
  { text: "Servindo de boa vontade como ao Senhor.", ref: "Efésios 6:7" },
  { text: "Porque melhor é a sabedoria do que as jóias.", ref: "Provérbios 8:11" },
  { text: "Não ameis o mundo nem o que nele há.", ref: "1 João 2:15" },
  { text: "Mas, se esperamos o que não vemos, com paciência o aguardamos.", ref: "Romanos 8:25" },
  { text: "Os que confiam no Senhor são como o monte de Sião.", ref: "Salmos 125:1" },
  { text: "Edificados sobre o fundamento dos apóstolos e dos profetas.", ref: "Efésios 2:20" },
  { text: "Guarda o teu coração, porque dele procedem as saídas da vida.", ref: "Provérbios 4:23" },
  { text: "Porque onde estiverem dois ou três reunidos em meu nome.", ref: "Mateus 18:20" },
  { text: "Porque há um só Deus e um só Mediador entre Deus e os homens.", ref: "1 Timóteo 2:5" },
  { text: "Vinde, e subamos ao monte do Senhor.", ref: "Isaías 2:3" },
  { text: "Envia a tua luz e a tua verdade, para que me guiem.", ref: "Salmos 43:3" },
  { text: "E recebereis poder, ao descer sobre vós o Espírito Santo.", ref: "Atos 1:8" },
  { text: "O homem bom tira boas coisas do bom tesouro do seu coração.", ref: "Lucas 6:45" },
  { text: "O Senhor é a minha força e o meu cântico.", ref: "Êxodo 15:2" },
  { text: "Ouve, ó Israel: O Senhor nosso Deus é o único Senhor.", ref: "Deuteronômio 6:4" },
  { text: "E tudo o que pedirdes na oração, crendo, o recebereis.", ref: "Mateus 21:22" },
  { text: "Porque o Senhor é justo; ele ama a justiça.", ref: "Salmos 11:7" },
  { text: "Assim brilhe a luz de vocês diante dos homens.", ref: "Mateus 5:16" },
  { text: "O Senhor é bom para todos.", ref: "Salmos 145:9" },
  { text: "E, se o meu povo, que se chama pelo meu nome, se humilhar.", ref: "2 Crônicas 7:14" },
  { text: "Deus é o nosso refúgio e fortaleza.", ref: "Salmos 46:1" },
  { text: "Se Deus é por nós, quem será contra nós?", ref: "Romanos 8:31" },
  { text: "Porque pelo fruto se conhece a árvore.", ref: "Mateus 12:33" },
  { text: "Humilhai-vos perante o Senhor, e ele vos exaltará.", ref: "Tiago 4:10" },
  { text: "E disse Deus: Haja luz; e houve luz.", ref: "Gênesis 1:3" },
  { text: "Bem-aventurados os puros de coração, porque verão a Deus.", ref: "Mateus 5:8" },
  { text: "E tudo o que fizerdes, fazei-o de todo o coração, como ao Senhor.", ref: "Colossenses 3:23" },
  { text: "Não fostes vós que me escolhestes a mim, mas eu vos escolhi a vós.", ref: "João 15:16" },
  { text: "Portanto, não se preocupem com o amanhã.", ref: "Mateus 6:34" },
  { text: "E a paz de Deus dominará em vossos corações.", ref: "Colossenses 3:15" },
  { text: "Tudo tem o seu tempo determinado.", ref: "Eclesiastes 3:1" },
  // Setembro (244-273)
  { text: "O Senhor te guarde de todo o mal; guarde a tua alma.", ref: "Salmos 121:7" },
  { text: "Porque o amor do dinheiro é a raiz de toda espécie de males.", ref: "1 Timóteo 6:10" },
  { text: "Quanto ao mais, irmãos, pensem em tudo o que é verdadeiro.", ref: "Filipenses 4:8" },
  { text: "Procura apresentar-te a Deus aprovado.", ref: "2 Timóteo 2:15" },
  { text: "Vós, porém, sois geração eleita, sacerdócio real.", ref: "1 Pedro 2:9" },
  { text: "Conta-me os teus caminhos, Senhor.", ref: "Salmos 25:4" },
  { text: "Porque o Senhor é grande e muito digno de louvor.", ref: "Salmos 96:4" },
  { text: "Os céus proclamam a glória de Deus.", ref: "Salmos 19:1" },
  { text: "Não te irrites por causa dos malfeitores.", ref: "Salmos 37:1" },
  { text: "Quem é como o Senhor nosso Deus?", ref: "Salmos 113:5" },
  { text: "O Senhor preserva os sinceros de coração.", ref: "Salmos 31:23" },
  { text: "E que pregueis o evangelho a toda criatura.", ref: "Marcos 16:15" },
  { text: "E a sua justiça permanece para sempre.", ref: "Salmos 112:3" },
  { text: "Orai sem cessar.", ref: "1 Tessalonicenses 5:17" },
  { text: "Nele estava a vida, e a vida era a luz dos homens.", ref: "João 1:4" },
  { text: "E haja em vós o mesmo sentimento que houve também em Cristo Jesus.", ref: "Filipenses 2:5" },
  { text: "Celebrai com júbilo ao Senhor, todos os moradores da terra.", ref: "Salmos 100:1" },
  { text: "Chegai-vos a Deus, e ele se chegará a vós.", ref: "Tiago 4:8" },
  { text: "Honra a teu pai e a tua mãe.", ref: "Êxodo 20:12" },
  { text: "Não faças do dinheiro o propósito da tua vida.", ref: "1 Timóteo 6:17" },
  { text: "Em ti, Senhor, busco refúgio.", ref: "Salmos 31:1" },
  { text: "Seja a vossa mansidão conhecida de todos os homens.", ref: "Filipenses 4:5" },
  { text: "Não há semelhante a ti, Senhor.", ref: "Jeremias 10:6" },
  { text: "Porque a letra mata, mas o Espírito vivifica.", ref: "2 Coríntios 3:6" },
  { text: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo.", ref: "1 Pedro 1:3" },
  { text: "E a graça de nosso Senhor se derramou abundantemente sobre mim.", ref: "1 Timóteo 1:14" },
  { text: "Antes de formar-te no ventre, eu te conheci.", ref: "Jeremias 1:5" },
  { text: "E edificarão os lugares antigamente assolados.", ref: "Isaías 61:4" },
  { text: "Quem subiu ao céu e desceu?", ref: "Provérbios 30:4" },
  { text: "Louvai ao Senhor, porque ele é bom.", ref: "Salmos 136:1" },
  // Outubro (274-304)
  { text: "Pois Cristo morreu uma vez pelos pecados.", ref: "1 Pedro 3:18" },
  { text: "Porque estou certo de que nem a morte nem a vida nos poderá separar do amor de Deus.", ref: "Romanos 8:38-39" },
  { text: "Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa.", ref: "Atos 16:31" },
  { text: "Sede também pacientes; fortalecei os vossos corações.", ref: "Tiago 5:8" },
  { text: "Cantai ao Senhor um cântico novo.", ref: "Salmos 96:1" },
  { text: "Porque Deus não é Deus de confusão, senão de paz.", ref: "1 Coríntios 14:33" },
  { text: "Vai ter com a formiga, ó preguiçoso.", ref: "Provérbios 6:6" },
  { text: "Conta ao Senhor os teus caminhos, confia nele.", ref: "Salmos 37:5" },
  { text: "A sabedoria é a coisa principal; adquire, pois, a sabedoria.", ref: "Provérbios 4:7" },
  { text: "E, indo eles pelo caminho, chegaram a certa água.", ref: "Atos 8:36" },
  { text: "Porque tudo o que há no mundo é passageiro.", ref: "1 João 2:17" },
  { text: "Guarda-te do mal e faze o bem.", ref: "Salmos 34:14" },
  { text: "Regozijai-vos na esperança.", ref: "Romanos 12:12" },
  { text: "E andai em amor, como também Cristo vos amou.", ref: "Efésios 5:2" },
  { text: "Ele é Senhor dos senhores e Rei dos reis.", ref: "Apocalipse 17:14" },
  { text: "Portanto ide, fazei discípulos de todas as nações.", ref: "Mateus 28:19" },
  { text: "Porque Deus está nos céus e tu estás na terra.", ref: "Eclesiastes 5:2" },
  { text: "Debruça-te para mim, e tem misericórdia de mim.", ref: "Salmos 86:16" },
  { text: "Sejam gratos.", ref: "Colossenses 3:15" },
  { text: "Faze o bem a todos.", ref: "Gálatas 6:10" },
  { text: "Digno é o Cordeiro que foi morto de receber poder.", ref: "Apocalipse 5:12" },
  { text: "Alegrem-se os céus, e regozije-se a terra!", ref: "Salmos 96:11" },
  { text: "E disse-lhe Jesus: Segue-me.", ref: "Mateus 9:9" },
  { text: "Porque somos cooperadores de Deus.", ref: "1 Coríntios 3:9" },
  { text: "Bem-aventurados os que sofrem perseguição por causa da justiça.", ref: "Mateus 5:10" },
  { text: "Aquele que crê em mim tem a vida eterna.", ref: "João 6:47" },
  { text: "O Senhor reina; ele se revestiu de majestade.", ref: "Salmos 93:1" },
  { text: "Não ameis o mundo nem o que nele há.", ref: "1 João 2:15" },
  { text: "O Senhor é o meu pastor; nada me faltará.", ref: "Salmos 23:1" },
  { text: "Bem-aventurado o homem que teme ao Senhor.", ref: "Salmos 112:1" },
  { text: "E todo o que vive e crê em mim nunca morrerá.", ref: "João 11:26" },
  // Novembro (305-334)
  { text: "Por isso não desanimamos; pelo contrário, mesmo que nosso homem exterior se corrompa.", ref: "2 Coríntios 4:16" },
  { text: "Não sejais vagarosos no cuidado.", ref: "Romanos 12:11" },
  { text: "E o seu reino não terá fim.", ref: "Lucas 1:33" },
  { text: "Não temas, porque eu te remi; chamei-te pelo teu nome.", ref: "Isaías 43:1" },
  { text: "Irmãos, não vos maravilheis se o mundo vos odeia.", ref: "1 João 3:13" },
  { text: "A vida consiste em fazer a vontade de Deus.", ref: "1 João 2:17" },
  { text: "Nada há que não possa fazer.", ref: "Lucas 1:37" },
  { text: "Em tudo dai graças.", ref: "1 Tessalonicenses 5:18" },
  { text: "Sede uns aos outros hospitaleiros, sem murmuração.", ref: "1 Pedro 4:9" },
  { text: "Por isso exorto-vos a que confirmeis o vosso amor para com ele.", ref: "2 Coríntios 2:8" },
  { text: "Ele que não conheceu pecado, Deus o fez pecado por nós.", ref: "2 Coríntios 5:21" },
  { text: "E sabemos que já passou da morte para a vida.", ref: "1 João 3:14" },
  { text: "Portanto, vede prudentemente como andais.", ref: "Efésios 5:15" },
  { text: "E não vos conformeis com este mundo.", ref: "Romanos 12:2" },
  { text: "Fazei todas as coisas sem murmurações nem contendas.", ref: "Filipenses 2:14" },
  { text: "E sobre tudo isto revesti-vos de amor.", ref: "Colossenses 3:14" },
  { text: "Porque o reino de Deus não é comida nem bebida.", ref: "Romanos 14:17" },
  { text: "E a nossa comunhão é com o Pai.", ref: "1 João 1:3" },
  { text: "A esperança não nos decepciona.", ref: "Romanos 5:5" },
  { text: "O Senhor é o meu ajudador, não temerei.", ref: "Hebreus 13:6" },
  { text: "Não olhando nós para as coisas que se veem.", ref: "2 Coríntios 4:18" },
  { text: "Trabalhai, não pela comida que perece.", ref: "João 6:27" },
  { text: "Porque onde há dois ou três congregados em meu nome.", ref: "Mateus 18:20" },
  { text: "Por isso não desanimamos.", ref: "2 Coríntios 4:1" },
  { text: "Não temas, pequeno rebanho.", ref: "Lucas 12:32" },
  { text: "Porque nada podemos contra a verdade.", ref: "2 Coríntios 13:8" },
  { text: "Fazei o bem a todos.", ref: "Gálatas 6:10" },
  { text: "Não vos canseis de fazer o bem.", ref: "2 Tessalonicenses 3:13" },
  { text: "Em tudo somos mais que vencedores.", ref: "Romanos 8:37" },
  { text: "Porque Deus é amor.", ref: "1 João 4:8" },
  // Dezembro (335-365)
  { text: "E ela dará à luz um filho, e lhe porás o nome de Jesus.", ref: "Mateus 1:21" },
  { text: "Porque um menino nos nasceu, um filho se nos deu.", ref: "Isaías 9:6" },
  { text: "Glória a Deus nas alturas, paz na terra aos homens a quem ele quer bem.", ref: "Lucas 2:14" },
  { text: "E o Verbo se fez carne e habitou entre nós.", ref: "João 1:14" },
  { text: "Eis que a virgem conceberá e dará à luz um filho.", ref: "Isaías 7:14" },
  { text: "E vieram apressadamente e acharam Maria, José e o menino.", ref: "Lucas 2:16" },
  { text: "E tu, Belém Efrata, posto que pequena entre os milhares de Judá.", ref: "Miqueias 5:2" },
  { text: "Vimos a sua estrela no oriente e viemos adorá-lo.", ref: "Mateus 2:2" },
  { text: "E, entrando na casa, acharam o menino com Maria.", ref: "Mateus 2:11" },
  { text: "Porque hoje vos nasceu, na cidade de Davi, o Salvador.", ref: "Lucas 2:11" },
  { text: "Todos os que o ouviam admiravam-se do seu entendimento.", ref: "Lucas 2:47" },
  { text: "E o menino crescia e se fortalecia em espírito.", ref: "Lucas 2:40" },
  { text: "E crescia Jesus em sabedoria, e em estatura.", ref: "Lucas 2:52" },
  { text: "Este é o meu mandamento: que vos ameis uns aos outros.", ref: "João 15:12" },
  { text: "Porque na esperança fomos salvos.", ref: "Romanos 8:24" },
  { text: "E vimos a sua glória, glória como do unigênito do Pai.", ref: "João 1:14" },
  { text: "E disse-lhes o anjo: Não temais.", ref: "Lucas 2:10" },
  { text: "Porque Deus enviou o seu Filho ao mundo.", ref: "João 3:17" },
  { text: "Em verdade, em verdade vos digo: quem ouve a minha palavra tem a vida eterna.", ref: "João 5:24" },
  { text: "E sabemos que o Filho de Deus é vindo.", ref: "1 João 5:20" },
  { text: "Porque há um só Deus e um só Mediador.", ref: "1 Timóteo 2:5" },
  { text: "E nele temos a redenção pelo seu sangue.", ref: "Efésios 1:7" },
  { text: "Porque eu sei em quem tenho crido.", ref: "2 Timóteo 1:12" },
  { text: "Pelejai a boa peleja da fé.", ref: "1 Timóteo 6:12" },
  { text: "Combati o bom combate, acabei a carreira, guardei a fé.", ref: "2 Timóteo 4:7" },
  { text: "Eis que venho sem demora.", ref: "Apocalipse 22:12" },
  { text: "Eis que faço novas todas as coisas.", ref: "Apocalipse 21:5" },
  { text: "A graça de nosso Senhor Jesus Cristo seja com todos vós.", ref: "Apocalipse 22:21" },
  { text: "Ora, àquele que é poderoso para vos guardar de tropeçar.", ref: "Judas 1:24" },
  { text: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo.", ref: "1 Pedro 1:3" },
  { text: "A Ele seja a glória, agora e eternamente. Amém.", ref: "2 Pedro 3:18" },
];

export function getDailyQuote(): { text: string; ref: string; dayOfYear: number } {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  // Use dayOfYear as index (0-364), wrap around if needed
  const quoteIndex = (dayOfYear - 1) % dailyQuotes.length;
  const quote = dailyQuotes[quoteIndex];
  
  return {
    ...quote,
    dayOfYear,
  };
}